/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#2b3549",
        "surface-container-low": "#121b2f",
        "inverse-surface": "#d9e2fd",
        "tertiary-container": "#009eb9",
        "surface": "#091326",
        "secondary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#07006c",
        "outline-variant": "#424754",
        "on-tertiary-fixed-variant": "#004e5c",
        "inverse-primary": "#005ac2",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#202a3e",
        "primary-container": "#4d8eff",
        "surface-container": "#161f33",
        "on-primary": "#002e6a",
        "on-error": "#690005",
        "tertiary": "#4cd7f6",
        "background": "#091326",
        "tertiary-fixed": "#acedff",
        "on-primary-fixed": "#001a42",
        "inverse-on-surface": "#273045",
        "on-tertiary": "#003640",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#93000a",
        "on-tertiary-container": "#002f38",
        "error": "#ffb4ab",
        "on-secondary": "#1000a9",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-container": "#3131c0",
        "surface-tint": "#adc6ff",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-dim": "#091326",
        "on-secondary-container": "#b0b2ff",
        "on-background": "#d9e2fd",
        "on-tertiary-fixed": "#001f26",
        "surface-container-lowest": "#040e21",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "secondary": "#c0c1ff",
        "on-primary-fixed-variant": "#004395",
        "on-surface": "#d9e2fd",
        "surface-bright": "#30394e",
        "on-primary-container": "#00285d",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-variant": "#2b3549"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "margin": "1.5rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "gutter-lg": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "metric-display": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "metric-display": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
